name: Publish Package to PyPi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      gitrelease:
        description: "Whether to release with a GitHub Release."
        required: true
        type: boolean
        default: true

jobs:
  publish:
    uses: Officer-Erik-1K-88/ThornForge/.github/workflows/publish.yml@main
    with:
      thornforge-ref: "main"
      gitrelease: ${{ github.event_name == 'push' || inputs.gitrelease }}
      environment: "publish"
      environment-name: "pypi"
      environment-project: "piethorn"