name: Publish Package to Test PyPi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  workflow_dispatch:

jobs:
  publish:
    uses: Officer-Erik-1K-88/ThornForge/./.github/workflows/publish.yml@main
    with:
      gitrelease: false
      thornforge-ref: "main"
      environment: "test"
      test-environment-name: "testpypi"
      test-environment-project: "piethorn"
